name: Update Bot

on:
  push:
    branches:
      - main

jobs:
  update_bot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Update bot
      run: |
        python3 -c "import os; from update import update_from_git; update_from_git('https://github.com/acejas67/discordbot.git', 'local_folder')"
